package com.b_lam.resplash.util

import com.b_lam.resplash.BuildConfig

/**
 * Whether the app was built with a `google-services.json`.
 *
 * Firebase reads its configuration from resources generated by the Google Services Gradle plugin,
 * so touching any Firebase API in a build without that file throws at runtime. Every call site is
 * guarded by this flag so the app stays usable when it is built without Firebase.
 */
val isFirebaseAvailable: Boolean
    get() = BuildConfig.FIREBASE_ENABLED
